---

- name: "Run apt update/upgrade/install"
  tags:
    - provision
    - provision-requirements
  hosts: minecraft
  pre_tasks:
    - raw: apt update && apt upgrade -y
    - action: setup
  tasks:
    - apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - git
          - python3
          - python3-pip
          - sudo
          - htop
          - iotop
          - vim
          - tmux
          - screen
          - bash-completion
          - python-is-python3
          - unzip
          - ufw

- name: "Install python packages"
  hosts: minecraft
  tags:
    - provision
    - provision-requirements
  tasks:
    - pip:
        name: "{{ packages }}"
      vars:
        packages:
          - pexpect

- name: "Setup users"
  tags:
    - provision
    - provision-users
  hosts: minecraft
  roles:
    - weareinteractive.users
  vars:
    users:
      - username: artemvang
        authorized_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFymCHA/alTfOL9gE04JsfRfELpuO6TczDhcJe45C9zi artemvang@kecyk.com"
        home_create: yes
        groups: ["sudo"]
        shell: /bin/bash
      - username: minecraft
        home_create: yes
        home: /app/minecraft
        group: "minecraft"
        shell: /bin/bash

- name: "Setup firewall"
  tags:
    - provision
    - provision-security
    - provision-security-firewall
  hosts: minecraft
  tasks:
    - name: "Reset firewall"
      ufw:
        state: reset
    - name: "Set rules"
      ufw:
        delete: "{{ item.delete | default(omit) }}"
        direction: "{{ item.direction | default(omit) }}"
        from_ip: "{{ item.from_ip | default(omit) }}"
        from_port: "{{ item.from_port | default(omit) }}"
        insert: "{{ item.insert | default(omit) }}"
        interface: "{{ item.interface | default(omit) }}"
        log: "{{ item.log | default(omit) }}"
        logging: "{{ item.logging | default(omit) }}"
        name: "{{ item.name | default(omit) }}"
        policy: "{{ item.policy | default(omit) }}"
        port: "{{ item.port | default(omit) }}"
        proto: "{{ item.proto | default(omit) }}"
        rule: "{{ item.rule | default('allow') }}"
        state: "{{ item.state | default(omit) }}"
        to_ip: "{{ item.to_ip | default(omit) }}"
        to_port: "{{ item.to_port | default(omit) }}"
      with_items:
        - { port: 22, rule: allow }
        - { port: 80, rule: allow }
        - { port: 443, rule: allow }
        - { port: 25565, rule: allow }
        - { port: 8080, rule: allow }
    - name: "Start firewall"
      ufw:
        state: enabled
        logging: "off"

- name: "Set timezone"
  tags:
    - provision
    - provision-timezone
  hosts: minecraft
  tasks:
    - when: ansible_date_time.tz != 'UTC'
      command: timedatectl set-timezone UTC

- name: "Install Minecraft"
  tags:
    - minecraft
    - minecraft-install
  hosts: minecraft
  roles:
    - minecraft
