- name: "Restart Minecraft"
  changed_when: true
  service:
    name: "{{ minecraft_service_name}}"
    state: restarted

- name: "Enable service"
  changed_when: true
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - "{{ minecraft_service_name }}.service"
    - "{{ minecraft_service_name }}.socket"

